name: iwantmyname Domain Blog
twitter: iwantmyname

# Plugins
markdown: redcarpet
pygments: yes

# Base URL for GitHub Pages, use `jekyll serve --baseurl ""` locally
baseurl: https://iwantmyname.com/blog

# Permalinks to match MovableType
permalink: /:year/:month/:title.html

paginate: 10
paginate_path: /page-:num/

# Don't publish future-dated posts
future: no

# Non-standard config settings for use throughout site
images_url: https://iwantmyname.com/blog/assets/images/content
