name: iwantmyname Domain Blog
twitter: iwantmyname

# Plugins
markdown: redcarpet
pygments: yes

# Base URL for GitHub Pages, use `jekyll serve --baseurl ""` locally
# This needs to be an absolute URL for the RSS feeds
baseurl: http://blog.iwantmyname.com

# Permalinks to match MovableType
permalink: /:year/:month/:title.html

paginate: 10
paginate_path: /page-:num/

# Non-standard config settings for use throughout site
images_url: /assets/images/content
